import { Budget, Vendor } from '../types/pr.types';
import {
  ApprovalDigestItem,
  AssistantUserContext,
  BackendEndpointSpec,
  BudgetOverviewSnapshot,
  HistoricalOrderInsight,
  QuoteComparisonOption,
  TaskDigestItem,
  VendorRecommendation,
} from '../types/ai.types';

export const MOCK_VENDORS: Vendor[] = [
  {
    id: 'ergofit',
    name: 'ErgoFit Solutions',
    rating: 4.8,
    location: 'Mumbai, India',
    phone: '+91 22 5550 1010',
    email: 'hello@ergofit.in',
    paymentTerms: 'Net 30',
    deliveryTime: '5-7 business days',
    category: 'Furniture & Fixtures',
  },
  {
    id: 'ergoworkspace',
    name: 'ErgoWorkspace India',
    rating: 4.9,
    location: 'Bangalore, India',
    phone: '+91 80 4433 2200',
    email: 'sales@ergoworkspace.in',
    paymentTerms: 'Net 30',
    deliveryTime: '5-7 business days',
    category: 'Ergonomic Furniture',
  },
  {
    id: 'officemax',
    name: 'OfficeMax Solutions',
    rating: 4.6,
    location: 'Mumbai, India',
    phone: '+91 22 4400 7711',
    email: 'sneha@officemax.in',
    paymentTerms: 'Net 45',
    deliveryTime: '10-12 business days',
    category: 'Office Furniture',
  },
  {
    id: 'dell',
    name: 'Dell Technologies',
    rating: 4.7,
    location: 'Bangalore, India',
    phone: '+91 80 6611 8800',
    email: 'enterprise.in@dell.com',
    paymentTerms: 'Net 30',
    deliveryTime: '7-10 business days',
    category: 'IT Equipment',
  },
  {
    id: 'aws',
    name: 'Amazon Web Services',
    rating: 4.9,
    location: 'Hyderabad, India',
    phone: '+91 40 6600 2200',
    email: 'renewals-india@amazon.com',
    paymentTerms: 'Annual Invoice',
    deliveryTime: 'Immediate',
    category: 'Cloud Infrastructure',
  },
  {
    id: 'officehub',
    name: 'OfficeHub',
    rating: 4.4,
    location: 'Pune, India',
    phone: '+91 20 7788 1450',
    email: 'support@officehub.in',
    paymentTerms: 'Net 15',
    deliveryTime: '3-5 business days',
    category: 'Office Supplies',
  },
  {
    id: 'kitchenpro',
    name: 'KitchenPro India',
    rating: 4.5,
    location: 'Mumbai, India',
    phone: '+91 22 5577 9988',
    email: 'quotes@kitchenpro.in',
    paymentTerms: 'Net 20',
    deliveryTime: '3-5 business days',
    category: 'Pantry Equipment',
  },
];

export const MOCK_BUDGETS: Budget[] = [
  {
    id: 'eng-mar-2026',
    name: 'Engineering Monthly Procurement - March 2026',
    department: 'Engineering',
    availableBalance: 215000,
    totalBudget: 2000000,
    currency: 'INR',
  },
  {
    id: 'eng-furniture-2026',
    name: 'Engineering Furniture Refresh',
    department: 'Engineering',
    availableBalance: 80000,
    totalBudget: 400000,
    currency: 'INR',
  },
  {
    id: 'it-capex-2026',
    name: 'IT Infrastructure Upgrade',
    department: 'IT',
    availableBalance: 725000,
    totalBudget: 1500000,
    currency: 'INR',
  },
  {
    id: 'admin-ops-2026',
    name: 'Admin Operations',
    department: 'Operations',
    availableBalance: 350000,
    totalBudget: 700000,
    currency: 'INR',
  },
];

export const AI_USER_CONTEXT: AssistantUserContext = {
  name: 'Samay Maurya',
  department: 'Engineering',
  role: 'Procurement Requester',
  location: 'Mumbai office',
  defaultBudgetName: 'Engineering Monthly Procurement - March 2026',
  approvalLimit: 275000,
  manager: 'Rajesh Kumar',
  financeApprover: 'Sarah Patel',
};

export const AI_HISTORICAL_ORDERS: HistoricalOrderInsight[] = [
  {
    id: 'PR-2026-089',
    vendor: 'ErgoFit Solutions',
    item: 'Ergonomic office chairs',
    orderedMonthsAgo: 2,
    quantity: 15,
    unitPrice: 2800,
    rating: 4.8,
    note: 'Delivered on time with strong user feedback.',
  },
  {
    id: 'PR-2026-071',
    vendor: 'ErgoWorkspace India',
    item: 'Standing desks',
    orderedMonthsAgo: 2,
    quantity: 8,
    unitPrice: 16500,
    rating: 4.9,
    note: 'Best-value vendor for ergonomic furniture in the last quarter.',
  },
  {
    id: 'PR-2026-044',
    vendor: 'Dell Technologies',
    item: 'Dell Latitude laptops',
    orderedMonthsAgo: 1,
    quantity: 12,
    unitPrice: 48000,
    rating: 4.7,
    note: 'Procurement cycle completed in 3 business days.',
  },
];

export const AI_PENDING_APPROVALS: ApprovalDigestItem[] = [
  {
    id: 'PR-2026-245',
    title: 'Dell Laptops × 5',
    requester: 'Priya Sharma',
    department: 'Engineering',
    amount: 225000,
    vendor: 'Dell Technologies',
    dueLabel: 'Overdue by 2 days',
    urgency: 'Urgent',
    justification: 'New team members are joining next week.',
  },
  {
    id: 'PR-2026-248',
    title: 'AWS Cloud Services (Annual)',
    requester: 'DevOps Team',
    department: 'Engineering',
    amount: 500000,
    vendor: 'Amazon Web Services',
    dueLabel: 'Due today',
    urgency: 'Due Today',
    justification: 'Production infrastructure renewal for the current environment.',
  },
  {
    id: 'PR-2026-251',
    title: 'Office Supplies Bundle',
    requester: 'Admin Team',
    department: 'Operations',
    amount: 15000,
    vendor: 'OfficeHub',
    dueLabel: 'Due in 3 days',
    urgency: 'This Week',
    justification: 'Monthly supplies restocking.',
  },
];

export const AI_VENDOR_RECOMMENDATIONS: VendorRecommendation[] = [
  {
    id: 'ergoworkspace',
    name: 'ErgoWorkspace India',
    rating: 4.9,
    specialization: 'Ergonomic furniture',
    previousOrders: 3,
    lastOrderLabel: '2 months ago',
    averageDelivery: '5-7 days',
    priceRange: '₹15,000 - ₹35,000 per desk',
    paymentTerms: 'Net 30',
    location: 'Bangalore (ships to Mumbai)',
    highlight: "You've ordered from them before with excellent feedback.",
  },
  {
    id: 'officemax',
    name: 'OfficeMax Solutions',
    rating: 4.6,
    specialization: 'Office furniture',
    previousOrders: 1,
    lastOrderLabel: '5 months ago',
    averageDelivery: '10-12 days',
    priceRange: '₹12,000 - ₹28,000 per desk',
    paymentTerms: 'Net 45',
    location: 'Mumbai (local vendor)',
    highlight: 'Local vendor with lower freight cost and easier issue resolution.',
  },
  {
    id: 'moderndesk',
    name: 'ModernDesk Co.',
    rating: 4.2,
    specialization: 'Premium workspace furniture',
    previousOrders: 0,
    averageDelivery: '7-10 days',
    priceRange: '₹18,000 - ₹40,000 per desk',
    paymentTerms: 'Net 30',
    location: 'Delhi NCR',
    highlight: 'Premium build quality and the longest standard warranty.',
  },
];

export const AI_TASKS: TaskDigestItem[] = [
  {
    id: 'approve-pr-245',
    title: 'Approve PR-2026-245',
    priority: 'Urgent',
    summary: 'Dell laptops for new hires',
    dueLabel: 'Overdue by 2 days',
    amountImpact: '₹2,25,000',
    ctaPrimary: 'Approve Now',
    ctaSecondary: 'View Details',
  },
  {
    id: 'review-standing-desk-quotes',
    title: 'Review Quote Comparison',
    priority: 'Urgent',
    summary: 'Standing desks with 3 vendor responses',
    dueLabel: 'Due today',
    amountImpact: 'Best price: ₹14,500 / desk',
    ctaPrimary: 'Compare Quotes',
    ctaSecondary: 'Select Vendor',
  },
  {
    id: 'complete-aws-renewal',
    title: 'Complete PR-2026-248',
    priority: 'This Week',
    summary: 'AWS renewal needs vendor contract review',
    dueLabel: 'Due in 2 days',
    ctaPrimary: 'Upload Contract',
    ctaSecondary: 'Mark Complete',
  },
  {
    id: 'budget-review-meeting',
    title: 'Budget Review Meeting',
    priority: 'This Week',
    summary: 'Q1 spending versus budget',
    dueLabel: 'March 19, 2026',
    ctaPrimary: 'View Report',
    ctaSecondary: 'Add to Calendar',
  },
  {
    id: 'goods-receipt',
    title: 'Approve Goods Receipt',
    priority: 'This Week',
    summary: 'Office chairs delivered and awaiting verification',
    dueLabel: 'GR-2026-123',
    ctaPrimary: 'Verify & Approve',
  },
  {
    id: 'monthly-report',
    title: 'Monthly Procurement Report',
    priority: 'Upcoming',
    summary: 'March summary for leadership review',
    dueLabel: 'Due March 25, 2026',
    ctaPrimary: 'Start Draft',
  },
];

export const AI_QUOTE_COMPARISON: QuoteComparisonOption[] = [
  {
    id: 'ergoworkspace',
    vendor: 'ErgoWorkspace India',
    unitPrice: 16500,
    totalPrice: 165000,
    warranty: '3 years',
    delivery: '5-7 days',
    paymentTerms: 'Net 30',
    highlight: 'Previous vendor with consistent quality',
    recommendationTag: 'Best Value',
  },
  {
    id: 'officemax',
    vendor: 'OfficeMax Solutions',
    unitPrice: 14500,
    totalPrice: 145000,
    warranty: '2 years',
    delivery: '10-12 days',
    paymentTerms: 'Net 45',
    highlight: 'Lowest landed cost and local support',
    recommendationTag: 'Lowest Price',
  },
  {
    id: 'moderndesk',
    vendor: 'ModernDesk Co.',
    unitPrice: 22000,
    totalPrice: 220000,
    warranty: '5 years',
    delivery: '7-10 days',
    paymentTerms: 'Net 30',
    highlight: 'Premium build with longest warranty',
    recommendationTag: 'Premium',
  },
];

export const AI_BUDGET_OVERVIEW: BudgetOverviewSnapshot = {
  department: 'Engineering',
  monthLabel: 'March 2026',
  totalBudget: 2000000,
  spentToDate: 1435000,
  committed: 350000,
  available: 215000,
  trendingNote: 'Spending is 15% higher than last month due to new team hires.',
  forecastNote: 'At the current run rate, March will exceed budget by roughly ₹50,000.',
  categories: [
    {
      name: 'IT Equipment',
      spent: 850000,
      total: 1000000,
      available: 150000,
      status: 'Healthy',
    },
    {
      name: 'Furniture',
      spent: 320000,
      total: 400000,
      available: 80000,
      status: 'Running Low',
    },
    {
      name: 'Software Licenses',
      spent: 265000,
      total: 300000,
      available: 35000,
      status: 'Critical',
    },
    {
      name: 'Office Supplies',
      spent: 100000,
      total: 500000,
      available: 400000,
      status: 'Excellent',
    },
  ],
  recommendations: [
    'Defer non-urgent software renewals to April.',
    'Combine office-supply orders for bulk discounts.',
    'Request a ₹1,00,000 increase for Q2 hiring preparation.',
  ],
};

export const AI_BACKEND_ENDPOINTS: BackendEndpointSpec[] = [
  {
    method: 'POST',
    path: '/api/ai/conversations/parse',
    purpose: 'Extract intent, entities, and confidence from natural language input.',
  },
  {
    method: 'POST',
    path: '/api/purchase-requests',
    purpose: 'Create a single purchase request from a confirmed AI draft.',
  },
  {
    method: 'POST',
    path: '/api/purchase-requests/bulk',
    purpose: 'Create grouped PRs for office setup and other multi-item workflows.',
  },
  {
    method: 'GET',
    path: '/api/purchase-requests/:id/approvals',
    purpose: 'Fetch approval chain, SLA, and approval status for a PR.',
  },
  {
    method: 'PATCH',
    path: '/api/approvals/bulk',
    purpose: 'Approve or reject multiple pending PRs in a single action.',
  },
  {
    method: 'GET',
    path: '/api/vendors/search',
    purpose: 'Search vendors with filters, recommendations, and historical order context.',
  },
  {
    method: 'POST',
    path: '/api/vendors/quotes/request',
    purpose: 'Send RFQ emails or quote requests to one or more vendors.',
  },
  {
    method: 'GET',
    path: '/api/quotes/comparisons/:workspaceId',
    purpose: 'Return quote comparison workspaces with AI recommendations.',
  },
  {
    method: 'GET',
    path: '/api/tasks/my',
    purpose: 'Retrieve pending approvals, reminders, reports, and delivery tasks for the current user.',
  },
  {
    method: 'GET',
    path: '/api/budgets/overview',
    purpose: 'Fetch real-time budget balances, committed spend, and category breakdowns.',
  },
  {
    method: 'POST',
    path: '/api/notifications/send',
    purpose: 'Dispatch emails, reminders, and workflow notifications triggered by AI actions.',
  },
];

export const AI_DASHBOARD_PR_OVERRIDES = [
  {
    id: 'PR-2026-089',
    vendors: ['ErgoFit Solutions'],
    status: 'Approved',
    createdBy: 'Samay Maurya',
    dueDate: '2026-01-28',
    createdAt: '2026-01-14',
    amount: 42000,
    department: 'Engineering',
    category: 'Furniture & Fixtures',
    lastUpdated: '2026-01-21',
  },
  {
    id: 'PR-2026-245',
    vendors: ['Dell Technologies'],
    status: 'Approval Pending',
    createdBy: 'Priya Sharma',
    dueDate: '2026-03-15',
    createdAt: '2026-03-03',
    amount: 225000,
    department: 'Engineering',
    category: 'IT Equipment',
    lastUpdated: '2026-03-12',
  },
  {
    id: 'PR-2026-248',
    vendors: ['Amazon Web Services'],
    status: 'Approval Pending',
    createdBy: 'DevOps Team',
    dueDate: '2026-03-17',
    createdAt: '2026-03-05',
    amount: 500000,
    department: 'Engineering',
    category: 'Cloud Infrastructure',
    lastUpdated: '2026-03-16',
  },
  {
    id: 'PR-2026-251',
    vendors: ['OfficeHub'],
    status: 'Approval Pending',
    createdBy: 'Admin Team',
    dueDate: '2026-03-20',
    createdAt: '2026-03-09',
    amount: 15000,
    department: 'Operations',
    category: 'Office Supplies',
    lastUpdated: '2026-03-15',
  },
];
